spring:
    cloud:
      gateway:
        routes:
          - id : r1
            uri: http://localhost:8081/
            predicates:
                - Path=/customers/**
          - id : r2
            uri: http://localhost:8082/
            predicates:
                - Path=/accounts/**
    application:
        name: gateway-service
eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka
server:
    port: 8888
